import serverEntry from "@tanstack/react-start/server-entry"
import { handleMcp } from "@/mcp.server"
import R2Budget from "@/durable-objects/r2-budget"

export { R2Budget }

declare module "@tanstack/react-router" {
  interface Register {
    server: {
      requestContext: {
        env: Env
        ctx: ExecutionContext
      }
    }
  }
}

const AI_CRAWLER_PATTERN =
  /(GPTBot|ChatGPT-User|Google-Extended|ClaudeBot|anthropic-ai|Bytespider|CCBot|PerplexityBot|Amazonbot|Meta-ExternalAgent|Applebot-Extended|cohere-ai|Diffbot|ImagesiftBot|omgili|FacebookBot|GoogleOther)/i

const PUBLIC_CACHE_PATH =
  /^\/api\/(image|media|poster|storyboard|storyboard-vtt|captions)\/[^/]+$/

function securityHeaders(response: Response, pathname: string): Response {
  const headers = new Headers(response.headers)
  headers.set("x-robots-tag", "noindex, nofollow, noarchive")
  headers.set("referrer-policy", "no-referrer")
  const cacheControl = headers.get("cache-control") ?? ""
  const publicCache =
    PUBLIC_CACHE_PATH.test(pathname) && /^public,/.test(cacheControl)
  headers.delete("cloudflare-cdn-cache-control")
  if (!publicCache) headers.set("cache-control", "private, no-store")
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  })
}

function isPublicRead(request: Request, pathname: string): boolean {
  if (request.method !== "GET" && request.method !== "HEAD") return false
  // Share pages are eight-character IDs generated by the upstream app.
  return (
    /^\/[A-Za-z0-9]{8}$/.test(pathname) || PUBLIC_CACHE_PATH.test(pathname)
  )
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url)

    // Keep the MCP protocol endpoint separate from the public application
    // boundary. Access JWT verification and MCP rate limiting happen inside
    // handleMcp, before any crawler denial or page handling can run.
    if (url.pathname === "/mcp") return handleMcp(request, env, ctx)

    const userAgent = request.headers.get("user-agent") || ""
    if (AI_CRAWLER_PATTERN.test(userAgent))
      return new Response("Not found", {
        status: 404,
        headers: {
          "cache-control": "private, no-store",
          "x-robots-tag": "noindex, nofollow, noarchive",
        },
      })

    if (url.pathname === "/robots.txt") {
      return new Response("User-agent: *\nDisallow: /\n", {
        headers: {
          "content-type": "text/plain; charset=utf-8",
          "cache-control": "private, no-store",
          "x-robots-tag": "noindex, nofollow, noarchive",
        },
      })
    }

    if (isPublicRead(request, url.pathname)) {
      const ip = request.headers.get("cf-connecting-ip") || "unknown"
      const limited = await env.RATE_LIMIT.limit({ key: ip })
      if (!limited.success)
        return new Response("Too Many Requests", {
          status: 429,
          headers: {
            "cache-control": "private, no-store",
            "retry-after": env.RATE_LIMIT_RETRY_AFTER,
          },
        })
    }

    try {
      return securityHeaders(
        await serverEntry.fetch(request, { context: { env, ctx } }),
        url.pathname,
      )
    } catch (error) {
      console.error("Worker request failed", error)
      return new Response("Internal server error", {
        status: 500,
        headers: { "cache-control": "private, no-store" },
      })
    }
  },
} satisfies ExportedHandler<Env>
